let greetings: string = "Hello world";

// greetings.toLowercase(); //here i have done spell mistake of calling the function --- Here TS suggest actual spell
console.log(greetings);

//number
// let userID: number=3213.8;
let userID= 123.6; //you can avoid writing :Data type ---bcz typescript is smart enough that automatically it can find.
// userID. //here after writing the userID. the mathematical related function displays

//boolean
let isLoggedIn: boolean=false;
export{}