const superHeros: string[] = [];
// const heroPower: number[] = [];
const heroPower: Array<number> = [];

type User= {
    name:string,
    age:number;
    gender?:string
}

const allUser: User[] = [];
const MLModels: number[][] = [
    [255, 255, 255],
    [454, 454, 666]
]
superHeros.push("superman");
heroPower.push(5);
allUser.push({name:"roshan", age:21, gender:"male"});
allUser.push({name:"Manish", age:25});